AWSTemplateFormatVersion: 2010-09-09

Parameters:
  mainStackName:
    Type: String  
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  RoleArn:
    Type: String

Resources:
  myCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref mainStackName
      Version: '1.21'
      RoleArn: !Ref RoleArn
      ResourcesVpcConfig:
        SubnetIds:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
        # SecurityGroupIds:
        #   - sg-6979fe18:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: prod
      NodeRole: 'arn:aws:iam::012345678910:role/eksInstanceRole'
      ScalingConfig:
        MinSize: 3
        DesiredSize: 5
        MaxSize: 7
      Labels:
        Key1: Value1
        Key2: Value2
      Subnets:
      - !Ref PublicSubnet1Id
      - !Ref PublicSubnet2Id