AWSTemplateFormatVersion: 2010-09-09
Description: words

Parameters:
  deploymentId:
    Type: String
    Default: asdf123
  cfS3Folder:
    Type: String
    Default: https://s3.amazonaws.com/turkeycfg/<env>/cf/
  turkeyDomain:
    Type: String
    Default: myhubs.net
  PGpwd:
    Type: String
    Default: itjfHE4HuS
  # VpcCIDR:
  #   Type: String
  #   Default: 10.0.0.0/16    
  # PublicSubnet1CIDR:
  #   Type: String
  #   Default: 10.0.1.0/24
  # PublicSubnet2CIDR:
  #   Type: String
  #   Default: 10.0.2.0/24

Resources:
####################################### network ###################################################
  network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref cfS3Folder, "network.yaml"] ]
      Parameters:
        mainStackName: !Ref "AWS::StackName"
        VpcCIDR: 10.0.0.0/16
        PublicSubnet1CIDR: 10.0.1.0/24
        PublicSubnet2CIDR: 10.0.2.0/24
        PrivateSubnet1CIDR: 10.0.101.0/24
        PrivateSubnet2CIDR: 10.0.102.0/24
############################################# db #############################################
  db:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${cfS3Folder}db.yaml
      Parameters:
        mainStackName: !Ref "AWS::StackName"
        DBInstanceClass: db.t3.micro
        DBAllocatedStorage: 20
        PGpwd: !Ref PGpwd
        PrivateSubnet1Id: !GetAtt network.Outputs.PrivateSubnet1
        PrivateSubnet2Id: !GetAtt network.Outputs.PrivateSubnet2
############################################# eks #############################################
  eks:
    Type: AWS::CloudFormation::Stack
    DependsOn: network
    Properties:
      TemplateURL: !Sub ${cfS3Folder}eks.yaml
      Parameters:
        mainStackName: !Ref "AWS::StackName"
        PublicSubnet1Id: !GetAtt network.Outputs.PublicSubnet1
        PublicSubnet2Id: !GetAtt network.Outputs.PublicSubnet2

Outputs:
  DB_HOST:
    Description: DB_HOST
    Value: !GetAtt db.Outputs.DB_HOST








###############################################################################################
  # HostedZone: 
  #   Type: "AWS::Route53::HostedZone"
  #   Properties: 
  #     HostedZoneConfig: 
  #       Comment: !Ref "AWS::StackName"
  #     Name: !Join ['', [!Ref "AWS::StackName", .]]
  #     VPCs: 
  #       - 
  #         VPCId: !Ref VPC
  #         VPCRegion: !Ref AWS::Region
  # RecordSet:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       DNSName: !GetAtt NLB.DNSName   
  #       HostedZoneId: !GetAtt NLB.CanonicalHostedZoneID
  #     Name: !Join ['.', [nlb, !Ref "AWS::StackName"]]
  #     Type: A
  #     HostedZoneId: !Ref HostedZone