AWSTemplateFormatVersion: 2010-09-09
Parameters:
  mainStackName:
    Type: String  
  retConfigSsmArn:
    Type: String    
  permsKeySsmArn:
    Type: String
Resources:  
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref mainStackName, exeRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  ExecutionRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: !Join ['-', [!Ref mainStackName, exeRole, ssmPolicy]]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: ssm:GetParameters
            Resource: 
            - !Ref retConfigSsmArn
            - !Ref permsKeySsmArn
      Roles: 
        - !Ref ExecutionRole
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref mainStackName, taskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - 'arn:aws:iam::aws:policy/AmazonCognitoPowerUser'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'        
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref mainStackName, hpaRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'
Outputs:
  ExecutionRole: 
    Description: "fargate-ExecutionRole"
    Value: !GetAtt ExecutionRole.Arn
  TaskRole: 
    Description: "fargate-TaskRole"
    Value: !GetAtt TaskRole.Arn
  AutoScalingRole: 
    Description: "fargate-AutoScalingRole"
    Value: !GetAtt AutoScalingRole.Arn