AWSTemplateFormatVersion: 2010-09-09

Parameters:
  mainStackName:
    Type: String
  assetsBucket:
    Type: String
  turkeyDomain:
    Type: String    
  albDNSname:
    Type: String
  turkeyCertArn:
    Type: String

Resources:
  lbCname:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref turkeyDomain, '.']]
      Comment: !Join ['', ["turkeyDeployment-lbCname-", !Ref mainStackName]]
      Name: !Sub ${mainStackName}.${turkeyDomain}
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !Ref albDNSname
  cdnCname:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref turkeyDomain, '.']]
      Comment: !Join ['', ["turkeyDeployment-cdn-", !Ref mainStackName]]
      Name: !Sub ${mainStackName}-cdn.${turkeyDomain}
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt retCDN.DomainName
  retCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:  
        Enabled: true
        Aliases:
          - !Sub ${mainStackName}.${turkeyDomain}
          - !Sub ${mainStackName}-cdn.${turkeyDomain}
        ViewerCertificate:
          AcmCertificateArn: !Ref turkeyCertArn
          SslSupportMethod: sni-only
        Origins:        
        - Id: !Sub ${mainStackName}-lb
          DomainName: !Ref albDNSname
          CustomOriginConfig:
            HTTPSPort: '443'
            OriginProtocolPolicy: https-only
        - Id: !Sub ${mainStackName}-assets
          DomainName: !Join ['', [!Ref assetsBucket, ".s3.amazonaws.com"]]
          S3OriginConfig:
            OriginAccessIdentity: ''
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          TargetOriginId:
            Fn::Sub: ${mainStackName}-assets
          ForwardedValues:
            QueryString: true
            Headers:
            - Origin
            - Content-Type
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Accept
            Cookies:
              Forward: none
          ViewerProtocolPolicy: https-only
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 3600
        CacheBehaviors:
        - PathPattern: /files/*
          Compress: true
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          TargetOriginId:
            Fn::Sub: ${mainStackName}-lb
          ForwardedValues:
            QueryString: true
            Headers:
            - Origin
            - Content-Type
            - Authorization
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Accept
            - Range
            Cookies:
              Forward: none
          ViewerProtocolPolicy: https-only
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 3600
        - PathPattern: /http*
          Compress: true
          AllowedMethods:
          - GET
          - HEAD
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          TargetOriginId:
            Fn::Sub: ${mainStackName}-lb
          ForwardedValues:
            QueryString: true
            Headers:
            - Origin
            - Content-Type
            - Range
            - Host
            - Authorization
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Accept
            Cookies:
              Forward: none
          ViewerProtocolPolicy: https-only
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 3600