apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2.2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        # # Only allow given email domains, can be set multiple times [$DOMAIN]
        # - name: DOMAIN
        #   value: myhubs.net
        - name: SECRET
          value: a-random-string-to-secure-your-cookie
        # - name: AUTH_HOST
        #   value: auth.myhubs.net
        - name: COOKIE_DOMAIN
          value: myhubs.net
        # # INSECURE_COOKIE is required unless using https entrypoint
        # - name: INSECURE_COOKIE
        #   value: "true"
        - name: DEFAULT_PROVIDER
          value: oidc
        - name: PROVIDERS_OIDC_ISSUER_URL
          value: https://kc.myhubs.net/auth/realms/master          
        - name: PROVIDERS_OIDC_CLIENT_ID
          value: traefik
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          value: 98ad903b-fac9-490e-a92f-a72b2519f2fa
---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181

# ---
# #
# # Auth Middleware
# #
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-forward-auth
# spec:
#   forwardAuth:
#     address: http://traefik-forward-auth:4181
#     authResponseHeaders:
#       - X-Forwarded-User
