apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-lb
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-lb
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.5
        imagePullPolicy: Always
        name: traefik-ingress-lb
        args:
        - --serversTransport.insecureSkipVerify=true
        - --providers.kubernetesingress=true       
        - --providers.kubernetescrd
        - --entryPoints.https.address=:443
        - --entryPoints.https.forwardedHeaders.insecure=true
        - --entryPoints.traefik.address=:1080
        - --api
        - --api.insecure
        - --accesslog
        - --log.level=INFO
        - --pilot.dashboard=false
        # - --entryPoints.web.address=:80
        # - --entrypoints.web.http.redirections.entryPoint.to=https
        # - --entrypoints.web.http.redirections.entryPoint.scheme=https
        # - --entrypoints.web.http.redirections.entrypoint.permanent=true
        # # # - --ping=true
        # - --certificatesresolvers.letsencrypt.acme.tlschallenge
        # - --certificatesresolvers.letsencrypt.acme.email=gtan@mozilla.com
        # - --certificatesresolvers.letsencrypt.acme.storage=acme.json
        
---
apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: traefik
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:558986605633:certificate/47d305ab-f861-470b-a837-98ca52a76e17
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  # - name: http
  #   port: 80
  #   targetPort: 80
  - name: https
    port: 443
    targetPort: 443   
  # - name: internal
  #   port: 444
  #   targetPort: 444  
  # - name: dashboard-test
  #   port: 1080
  #   targetPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - name: dashboard
    port: 1080
    targetPort: 1080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
  # annotations:
  #   ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
spec:
  entryPoints:
    - https
    # - web
  routes:
  - kind: Rule
    match: Host(`traefik.myhubs.net`) && PathPrefix(`/`)
    # middlewares:                    
    # - name: internal-ip-whitelist             
    #   namespace: traefik            
    services:                       
    - kind: Service
      name: dashboard
      namespace: traefik
      passHostHeader: true
      port: 1080

################### middlewares ##########################

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: rewrite4cdn
#   namespace: traefik
# spec:
#   stripPrefix:
#     prefixes: 
#       - /_cdn    
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: internal-ip-whitelist
#   namespace: traefik
# spec:
#   ipWhiteList:
#     sourceRange:
#       # - 10.0.0.0/16
#       - 73.53.171.231/32  # gtan@mozilla.com
#     # ipStrategy:
#     #   depth: 2
####################################################################################
################################### RBAC ###########################################
####################################################################################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-lb
  namespace: traefik
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-lb
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-lb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-lb
subjects:
- kind: ServiceAccount
  name: traefik-ingress-lb
  namespace: traefik 