
apiVersion: v1
kind: Namespace
metadata:
  name: turkey-services
---
####################################################################################
####################################### auth #######################################
####################################################################################  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: turkey-auth
  namespace: turkey-services
spec:
  entryPoints:
    - https
  routes:
  - kind: Rule
    match: Host(`auth.myhubs.net`) && PathPrefix(`/`)
    # middlewares:
    # - name: turkeyauth
    #   namespace: turkey-services    
    services:
    - kind: Service
      name: auth
      passHostHeader: true
      port: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: turkey-services
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: mozillareality/turkeyauth:36
        imagePullPolicy: IfNotPresent
        name: turkeyauth
        env:
        - name: SECRET
          value: a-random-string-to-secure-your-cookie
        - name: trusted_IPs
          value: 73.53.171.231,107.137.66.24
        - name: oauthClientId_google
          value: 329616299969-qdj49c50rqqokk2vialrm6l7nljfa0j5.apps.googleusercontent.com
        - name: oauthClientSecret_google
          value: g4QmxQI3gmCJg5G1DDHP4oBq          
        resources:
          limits:
            memory: 1024Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 0.1   
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: turkey-services
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - name: http
    port: 9001
    targetPort: 9001
---
####################################################################################
######################################### api ######################################
####################################################################################
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: turkey-api
  namespace: turkey-services
spec:
  entryPoints:
    - https
  routes:
  - kind: Rule
    match: Host(`api.myhubs.net`) && PathPrefix(`/`)
    # middlewares:
    # - name: turkeyauth
    #   namespace: turkey-services    
    services:
    - kind: Service
      name: turkey-api
      passHostHeader: true
      port: 888
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: turkeyauth
  namespace: turkey-services
spec:
  forwardAuth:
    address: http://api.turkey-services:9001/traefik-ip
    authResponseHeaders:
      - X-Forwarded-User
    trustForwardHeader: true      
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: turkey-services
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXOTZhV3hzWVhKbFlXeHBkSGs2Y21Wd2IzSjBJR0psWjJGMElIWmxjM1J0Wlc1MElHRnNkbVZ2YkdGeUlHTnNiM1JvIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: turkey-api
  namespace: turkey-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turkey-api
  minReadySeconds: 15                                      
  template:
    metadata:
      labels:
        app: turkey-api
    spec:
      serviceAccountName: api-sa
      containers:
      - image: mozillareality/turkeyapi:6
        imagePullPolicy: IfNotPresent
        name: turkey-orc
        livenessProbe:
          httpGet:
            path: "http://turkey-api.turkey-services/healthz"
            port: 888
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 120
        resources:
          limits:
            memory: 1024Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 0.1
      imagePullSecrets:
      - name: regcred      
---
apiVersion: v1
kind: Service
metadata:
  name: turkey-api
  namespace: turkey-services
spec:
  ports:
  - name: http
    port: 888
    targetPort: 888
  selector:
    app: turkey-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: turkey-services
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  
subjects:
- kind: ServiceAccount
  name: api-sa
  namespace: turkey-services

