
apiVersion: v1
kind: Namespace
metadata:
  name: turkey-stream
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turkey-https2
  namespace: turkey-stream
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: https2
spec:
  rules:
  - host: stream.myhubs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dialog
            port: 
              number: 4443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turkey-turn
  namespace: turkey-stream
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: turn
spec:
  rules:
  - host: stream.myhubs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coturn
            port: 
              number: 5349    
---
########################################################################
######################   dialog   ######################################
########################################################################  
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dialog
  namespace: turkey-stream
spec:
  selector:
    matchLabels:
      app: dialog
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: dialog
    spec:
      hostNetwork: true
      containers:
        - image: mozillareality/dialog:16
          imagePullPolicy: Always
          name: dialog
          env:
          - name: perms_key
            valueFrom:
              secretKeyRef:
                name: configs
                key: PERMS_KEY          
          livenessProbe:
            httpGet:
              path: "http://dialog.turkey-stream"
              port: 1111
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 120
          resources:
            limits:
              memory: 999Gi
              cpu: 999
---
apiVersion: v1
kind: Service
metadata:
  name: dialog
  namespace: turkey-stream
spec:
  ports:
  - name: https-dialog
    port: 4443
    targetPort: 4443
  - name: https-dialog-adm
    port: 7000
    targetPort: 7000
  selector:
    app: dialog
---
########################################################################
######################   coturn   ######################################
########################################################################
apiVersion: apps/v1
kind: DaemonSet                                          
metadata:
  name: coturn
  namespace: turkey-stream
spec:
  selector:
    matchLabels:
      app: coturn                                          
  minReadySeconds: 15                                      
  template:
    metadata:
      labels:
        app: coturn
    spec:
      hostNetwork: true
      containers:
        - image: mozillareality/coturn:12
          imagePullPolicy: Always
          name: coturn
          env:
          - name: REALM
            value: myhubs.net
          - name: PSQL
            value: postgresql://postgres:itjfHE4HuS@geng-test4turkey-db.ccgehrnbveo1.us-east-1.rds.amazonaws.com/ret_dev                      
          livenessProbe:
            httpGet:
              path: "http://coturn.turkey-stream"
              port: 1111
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 120
          resources:
            limits:
              memory: 999Gi
              cpu: 999
---
apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: turkey-stream
spec:
  ports:
  - name: https-coturn
    port: 5349
    targetPort: 5349
  selector:
    app: coturn