# This is a basic workflow to help you get started with Actions

name: api

on:
  push:
    branches: [ master, staging, dev ]
    paths:
    - 'api/**'
    - '.github/workflows/api.yml'
  workflow_dispatch:

env:
  containerName: turkeyapi
  registryName: mozillareality
  eksName_dev: turkey-dev
  eksName_staging: notyet
  eksName_prod: notyet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          cd ./api
          sed -i "s/##runNum##/${GITHUB_RUN_NUMBER}/g" ./_statics/console.html
          sed -i "s/##commitNum##/${GITHUB_SHA:0:7}/g" ./_statics/console.html
          docker build -q -t mozillareality/$containerName:$GITHUB_RUN_NUMBER .
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin
          sudo docker images
          sudo docker push $registryName/$containerName:$GITHUB_RUN_NUMBER
          echo "GITHUB_REF==$GITHUB_REF"
          if [ "$GITHUB_REF" = "refs/heads/dev" ] || [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "pushing :dev for $GITHUB_REF"
            docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev-$GITHUB_RUN_NUMBER
            sudo docker push $registryName/$containerName:dev-$GITHUB_RUN_NUMBER; fi
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "pushing :prod for $GITHUB_REF"
            docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod-$GITHUB_RUN_NUMBER
            sudo docker push $registryName/$containerName:prod-$GITHUB_RUN_NUMBER; fi
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: deploy container to dev cluster
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws eks update-kubeconfig --name $eksName_dev
          kubectl -n turkey-services set image deployment/turkey-api turkey-orc=$registryName/$containerName:$GITHUB_RUN_NUMBER

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - name: deploy container to dev cluster
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws eks update-kubeconfig --name $eksName_staging
          kubectl -n turkey-services set image deployment/turkey-api turkey-orc=$registryName/$containerName:$GITHUB_RUN_NUMBER

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    steps:
      - name: deploy container to dev cluster
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws eks update-kubeconfig --name $eksName_prod
          kubectl -n turkey-services set image deployment/turkey-api turkey-orc=$registryName/$containerName:$GITHUB_RUN_NUMBER
