name: coturn-docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUB_IP_CURL: https://ipinfo.io/ip


    steps:
      - name: docker
        run: |
          mkdir _tmp && cd _tmp
          
          cat > Dockerfile << 'EOL'
          from node:lts as build
          run mkdir certs && openssl req -x509 -newkey rsa:4096 -sha256 -days 36500 -nodes -keyout certs/key.pem -out certs/cert.pem -subj '/CN=dialog'
          from coturn/coturn:alpine
          copy --from=build /certs /certs
          user root:root
          run apk add curl
          run printf ' \n\
              export internalIp="0.0.0.0" \n\
              export externalIp="$(curl ${{ env.PUB_IP_CURL }})" \n\
              echo "externalIp: $externalIp" \n\
              echo "tls-listening-port=5349" > /etc/turnserver.conf \n\
              echo "cert=/certs/key.pem" >> /etc/turnserver.conf \n\
              echo "pkey=/certs/cert.pem" >> /etc/turnserver.conf \n\
              echo "realm=$coturn_realm" >> /etc/turnserver.conf \n\
              echo "listening-ip=$internalIp" >> /etc/turnserver.conf \n\
              echo "relay-ip=$externalIp" >> /etc/turnserver.conf \n\
              echo "external-ip=$externalIp" >> /etc/turnserver.conf \n\
              echo "allowed-peer-ip=$externalIp" >> /etc/turnserver.conf \n\
              /usr/local/bin/docker-entrypoint.sh --log-file=stdout' >> /init.sh
          run cat /init.sh && chmod +x /init.sh
          # user nobody:nogroup
          volume ["/var/lib/coturn"]
          cmd /init.sh
          EOL
          docker build -t ${{ secrets.DOCKER_HUB_USR }}/coturn:dev .
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username ${{ secrets.DOCKER_HUB_USR }} --password-stdin             
          sudo docker push ${{ secrets.DOCKER_HUB_USR }}/coturn:dev          
