name: deps_ytdl-api
on:
  push:
    branches: [ master, dev ]
    paths:
    - 'deps/ytdl/api_flask/*'
    - '.github/workflows/deps_ytdl-api.yml'
  workflow_dispatch:
env:
  containerName: ytdl
  registryName: mozillareality
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build + push
        run: |
          ytdlVer=$(curl https://pypi.org/pypi/youtube_dl/json | jq -r '.info.version')
          cd ./deps/ytdl/api_flask
          tag="$registryName/$containerName:${GITHUB_RUN_NUMBER}_$ytdlVer"
          echo "[info] tag: $tag"
          docker build . -t $tag
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          sudo docker push $tag
      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email:  hubs-dev-sa@hubs-dev-333333.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_HUBS_DEV_SA_JSON }}
          export_default_credentials: true
      - name: pushing to gcr
        run: |
          echo "[info] pushing to gcr"
          gcrtag="gcr.io/hubs-dev-333333/$containerName:${GITHUB_RUN_NUMBER}_$ytdlVer"
          gcloud auth configure-docker
          docker tag $tag $gcrtag && docker push $gcrtag
        