name: deps_ytdl-api
on:
  push:
    branches: [ master, dev ]
    paths:
    - 'deps/ytdl/api_flask/*'
    - '.github/workflows/deps_ytdl-api.yml'
  workflow_dispatch:
env:
  containerName: ytdl
  registryName: mozillareality
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build + push
        env:
          GOOGLE_APPLICATION_CREDENTIALS: gcpsakey
        run: |
          curl -sSL https://sdk.cloud.google.com | bash      
          /home/runner/google-cloud-sdk/bin/gcloud --version
          echo "${{ secrets.GCP_HUBS_DEV_SA_JSON }}" > gcpsakey && ls -lha gcpsakey
          
          ytdlVer=$(curl https://pypi.org/pypi/youtube_dl/json | jq -r '.info.version')
          cd ./deps/ytdl/api_flask
          tag="$registryName/$containerName:${GITHUB_RUN_NUMBER}_$ytdlVer"
          echo "[info] tag: $tag"
          docker build . -t $tag
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          sudo docker push $tag

          echo "[info] pushing to gcr"              
          /home/runner/google-cloud-sdk/bin/gcloud auth configure-docker
          gcrtag="gcr.io/hubs-dev-333333/$containerName:${GITHUB_RUN_NUMBER}_$ytdlVer"          
          docker tag $tag $gcrtag && docker push $gcrtag
        