
name: certbotbot_http
on:
  push:
    branches: [ master ]
    paths:
    - 'deps/certbotbot/Dockerfile_http'
    - 'deps/certbotbot/entrypoint.sh'
    - '.github/workflows/deps_certbotbot_http.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: deps/certbotbot
      registry: mozillareality
      dockerfile: Dockerfile_http
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
