name: deps_ytdl-api
on:
  push:
    branches: [ master, dev ]
    paths:
    - 'deps/ytdl/flask/*'
    - '.github/workflows/deps_ytdl-api.yml'
  workflow_dispatch:
env:
  containerName: ytdl
  registryName: mozillareality
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build + push
        run: |
          ytdlVer=$(curl https://pypi.org/pypi/youtube_dl/json | jq -r '.info.version')
          cd ./deps/ytdl/api_flask
          tag="$registryName/$containerName:${GITHUB_RUN_NUMBER}_$ytdlVer"
          echo "[info] tag: $tag"
          docker build . -t $tag
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          sudo docker push $tag
          

