
name: nearspark_gcr
on:
  push:
    branches: [ master ]
    paths:
    # - 'deps/nearspark/**'
    - '.github/workflows/deps_nearspark_gcr.yml'
  workflow_dispatch:
env:
  containerName: nearspark
  registryNameFrom: mozillareality
jobs:
  # turkeyGitops:
  #   uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
  #   with:
  #     codePath: deps/nearspark
  #     registry: mozillareality
  #     dockerfile: Dockerfile
  #   secrets:
  #     DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
  pushGcr:
    runs-on: ubuntu-latest
    steps:
    - name: dockerhub -> gcr      
      run: |      
        echo "[info] pushing to gcr"   
        echo "${{ secrets.GCP_HUBS_DEV_SA_JSON_b64 }}" | base64 -d > gcpsakey.json
        tag="$registryNameFrom/$containerName:latest"
        gcrtag="gcr.io/hubs-dev-333333/$containerName:latest" && echo "[info] gcrtag: $gcrtag"          
        gcloud auth activate-service-account hubs-dev-sa@hubs-dev-333333.iam.gserviceaccount.com --key-file=gcpsakey.json
        gcloud auth configure-docker -q gcr.io
        docker pull $tag
        docker tag $tag $gcrtag
        docker push $gcrtag      
