
name: pgbouncer
on:
  push:
    branches: [ master ]
    paths:
    - 'deps/pgbouncer/**'
    - '.github/workflows/deps_pgbouncer.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: deps/pgbouncer
      registry: mozillareality
      dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}

# # This is a basic workflow to help you get started with Actions

# name: deps_pgbouncer

# on:
#   push:
#     branches: [ master, dev ]
#     paths:
#     - 'deps/pgbouncer/**'
#     - '.github/workflows/deps_pgbouncer.yml'
#   workflow_dispatch:

# env:
#   containerName: pgbouncer
#   registryName: mozillareality

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: docker build
#         run: |
#           cd ./deps/pgbouncer
#           docker build -t mozillareality/$containerName:$GITHUB_RUN_NUMBER .
#           echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
#           sudo docker images
#           sudo docker push $registryName/$containerName:$GITHUB_RUN_NUMBER
#           echo "GITHUB_REF==$GITHUB_REF"
#           if [ "$GITHUB_REF" = "refs/heads/dev" ] || [ "$GITHUB_REF" = "refs/heads/master" ]; then
#             echo "pushing :dev for $GITHUB_REF"
#             docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev
#             sudo docker push $registryName/$containerName:dev; fi
#           if [ "$GITHUB_REF" = "refs/heads/master" ]; then
#             echo "pushing :prod for $GITHUB_REF"
#             docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod
#             sudo docker push $registryName/$containerName:prod; fi
#   # push-dev:
#   #   runs-on: ubuntu-latest
#   #   needs: build
#   #   environment:
#   #     name: dev
#   #   steps:
#   #     - name: pull <GITHUB_RUN_NUMBER>, re-tag to dev, push
#   #       run: |
#   #         echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
#   #         docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
#   #         docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev
#   #         sudo docker push $registryName/$containerName:dev
#   # push-prod:
#   #   if: github.ref == 'refs/heads/master'
#   #   runs-on: ubuntu-latest
#   #   needs: push-dev
#   #   environment:
#   #     name: prod
#   #   steps:
#   #     - name: pull <GITHUB_RUN_NUMBER>, re-tag to prod, push
#   #       run: |
#   #         echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
#   #         docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
#   #         docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod
#   #         sudo docker push $registryName/$containerName:prod
