name: deps_ytdl-api
on:
  push:
    branches:
    paths:
    - 'deps/ytdl/api_flask/*'
    - '.github/workflows/deps_ytdl-api.yml'
  workflow_dispatch:
env:
  containerName: ytdl
  registryName: mozillareality
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build + push          
        run: |
          #ytdlVer=$(curl https://pypi.org/pypi/youtube_dl/json | jq -r '.info.version')
          cd ./deps/ytdl/api_flask
          tag="$registryName/$containerName:${GITHUB_RUN_NUMBER}_v$ytdlVer"
          echo "[info] tag: $tag"
          docker build . -t $tag
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          sudo docker push $tag

          echo "[info] pushing to gcr"   
          echo "${{ secrets.GCP_HUBS_DEV_SA_JSON_b64 }}" | base64 -d > gcpsakey.json
          gcrtag="gcr.io/hubs-dev-333333/$containerName:${GITHUB_RUN_NUMBER}_v$ytdlVer" && echo "[info] gcrtag: $gcrtag"          
          gcloud auth activate-service-account hubs-dev-sa@hubs-dev-333333.iam.gserviceaccount.com --key-file=gcpsakey.json
          gcloud auth configure-docker -q gcr.io
          docker tag $tag $gcrtag && docker push $gcrtag
        