
name: certbotbot_google
on:
  push:
    branches: [ master ]
    paths:
    - 'deps/certbotbot/Dockerfile_google'
    - 'deps/certbotbot/entrypoint.sh'
    - '.github/workflows/deps_certbotbot_google.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: deps/certbotbot
      registry: mozillareality
      dockerfile: Dockerfile_google
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
