
name: certbotbot_route53
on:
  push:
    branches:
    paths:
    - 'deps/certbotbot/Dockerfile_route53'
    - 'deps/certbotbot/entrypoint.sh'
    - '.github/workflows/deps_certbotbot_route53.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: deps/certbotbot
      registry: mozillareality
      dockerfile: Dockerfile_route53
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
