name: dip
on:
  push:
    branches: 
    paths:
    - 'dip/**'
    - '.github/workflows/dip.yml'
  workflow_dispatch:
#11111
jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@feature/turkeysmokepipe
    with:
      codePath: dip
      registry: mozillareality
      dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
