name: hubs-rawhubs-s3
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-hubs
        uses: actions/checkout@v2
        with:
          repository: mozilla/hubs
          path: './hubs'
      - name: build rawhubs (unconfigured hubs and admin)
        run: |
          export BASE_ASSETS_PATH="{{rawhubs-base-assets-path}}"
          cd hubs && npm ci && npm run build
          cd admin && npm ci && npm run build && cp -R dist/* ../dist && cd ..
          mkdir -p dist/pages && mv dist/*.html dist/pages && mv dist/hub.service.js dist/pages && mv dist/schema.toml dist/pages
      - name: push to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.turkeycfg_aws_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.turkeycfg_aws_key }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync ./dist s3://turkeycfg/rawhubs
