name: hubs-rawhubs-s3
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-hubs
        uses: actions/checkout@v2
        with:
          repository: mozilla/hubs
          path: './hubs'
      - name: build rawhubs (unconfigured hubs and admin)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.turkeycfg_aws_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.turkeycfg_aws_key }}
          AWS_DEFAULT_REGION: us-east-1      
        run: |
          export BASE_ASSETS_PATH="{{rawhubs-base-assets-path}}"
          cd hubs && npm ci > /dev/null && npm run build > /dev/null
          cd admin && npm ci > /dev/null && npm run build > /dev/null && cp -R dist/* ../dist && cd ..
          mkdir -p dist/pages && mv dist/*.html dist/pages && mv dist/hub.service.js dist/pages && mv dist/schema.toml dist/pages
          aws s3 rm --recursive s3://turkeycfg/rawhubs > /dev/null
          aws s3 sync ./dist/assets s3://turkeycfg/rawhubs/assets > /dev/null
          aws s3 sync ./dist/pages s3://turkeycfg/rawhubs/pages > /dev/null
          aws s3 sync ./dist/favicon.ico s3://turkeycfg/rawhubs/pages > /dev/null
          aws s3 sync ./dist/react-components s3://turkeycfg/rawhubs/pages/react-components > /dev/null
          

