name: hubs
on:
  push:
    branches: [ master, dev ]
    paths:
    - '.github/workflows/hubs.yml'
  workflow_dispatch:

env:
  containerName: hubs
  registryName: mozillareality

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-hubs
        uses: actions/checkout@v2
        with:
          repository: mozilla/hubs
          ref: feature/turkey
          path: './hubs'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build and wrap rawhubs in nginx container
        run: |
          cd ./hubs/
          docker build . -t $registryName/$containerName:$GITHUB_RUN_NUMBER -f RetPageOriginDockerfile --cache-from "type=gha" --cache-to "type=gha,mode=max" 1>/dev/null
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin
          sudo docker push $registryName/$containerName:$GITHUB_RUN_NUMBER
          
  push-dev:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to dev, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
          docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev
          sudo docker push $registryName/$containerName:dev
  push-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: push-dev
    environment:
      name: prod
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to prod, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
          docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod
          sudo docker push $registryName/$containerName:prod          
