name: ita
on:
  push:
    branches: [ master ]
    paths:
    - 'ita/**'
    - '.github/workflows/ita.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@feature/multirepo-support-for-turkeyGitops
    with:
      codePath: ita
      registry: mozillareality
      dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}