# This is a basic workflow to help you get started with Actions

name: orchestrator

on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          cd ./orchestrator
          docker build -t mozillareality/turkeyorc:$GITHUB_RUN_NUMBER .
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username ${{ secrets.DOCKER_HUB_USR }} --password-stdin             
          sudo docker images
          sudo docker push ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:$GITHUB_RUN_NUMBER          
  push-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to dev, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username ${{ secrets.DOCKER_HUB_USR }} --password-stdin             
          docker pull ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:$GITHUB_RUN_NUMBER
          docker tag ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:dev
          sudo docker push ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:dev
  push-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: push-dev
    environment:
      name: prod
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to prod, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username ${{ secrets.DOCKER_HUB_USR }} --password-stdin             
          docker pull ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:$GITHUB_RUN_NUMBER
          docker tag ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:prod
          sudo docker push ${{ secrets.DOCKER_HUB_USR }}/turkeyorc:prod
