# This is a basic workflow to help you get started with Actions

name: ret-bio-docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIO_PKG_ORG: dummy1

    steps:
      - name: checkout-ret
        uses: actions/checkout@v2
        with:
          repository: mozilla/reticulum
          path: './ret'          
          
      - name: add-extra-hab-configs
        run: |
          cd ./ret/habitat/config/
          cat >> config.toml << EOL
          {{#if cfg.meta.phx_host}}
          [ret."Elixir.Ret.Meta"]
          phx_host = "{{ cfg.meta.phx_host }}"
          {{/if}}
          EOL
          cat config.toml
          
      - name: bio-pkg-build-export
        run: |          
          sudo docker --version
          cd ./ret
          org="biome-sh";repo="biome"
          ver=$(curl -s https://api.github.com/repos/$org/$repo/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3)}')
          dl="https://github.com/$org/$repo/releases/download/$ver/bio-${ver#"v"}-x86_64-linux.tar.gz"
          echo "[info] getting bio from: $dl"
          curl -L -o bio.gz $dl;
          tar -xf bio.gz;./bio --version          
          sudo ./bio origin key generate ${{ env.BIO_PKG_ORG }}
          sudo HAB_ORIGIN_KEYS=${{ env.BIO_PKG_ORG }} HAB_ORIGIN=${{ env.BIO_PKG_ORG }} ./bio pkg build . > /dev/null
          sudo HAB_ORIGIN_KEYS=${{ env.BIO_PKG_ORG }} HAB_ORIGIN=${{ env.BIO_PKG_ORG }} ./bio pkg export container ./results/*.hart > /dev/null
          
      - name: repackage-docker-with-certs
        run: |
          mkdir tmp && cd tmp
          cat > Dockerfile << EOL
          from alpine/openssl:latest as builder
          workdir /certs
          run openssl req -x509 -newkey rsa:2048 -sha256 -days 36500 -nodes -keyout ssl.key -out ssl.pem -subj '/CN=hubs'
          run cp ssl.pem ssl-chain.pem
          from ${{ env.BIO_PKG_ORG }}/reticulum
          WORKDIR /hab/svc/reticulum/files
          copy --from=builder /certs .
          run chown -R hab:hab ./* && ls -lha
          run printf 'while true; do { res="HTTP/1.1 200 OK\\r\\n";echo -e $res; } | nc -l -q 1 1111; done' > /healthcheck.sh && chmod +x /healthcheck.sh
          run printf ' \n\  
            #/healthcheck.sh& \n\
            export NODE_NAME="\$HOSTNAME" \n\
            export NODE_COOKIE="UmV0aWN1bHVt" \n\
            echo "pg2: \$NODE_NAME(\$NODE_COOKIE)" \n\ 
            bash /init.sh run ${{ env.BIO_PKG_ORG }}/reticulum \n\' > /run.sh
          run cat /run.sh
          entrypoint bash /run.sh
          EOL
          docker build -t ${{ env.BIO_PKG_ORG }}/reticulum:latest .          
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username ${{ secrets.DOCKER_HUB_USR }} --password-stdin             
          sudo docker tag ${{ env.BIO_PKG_ORG }}/reticulum:latest ${{ secrets.DOCKER_HUB_USR }}/ret:latest    
          sudo docker images
          sudo docker push ${{ secrets.DOCKER_HUB_USR }}/ret:latest
          
          


