# This is a basic workflow to help you get started with Actions

name: ret-bio-docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-ret
        uses: actions/checkout@v2
        with:
          repository: mozilla/reticulum
          path: './ret'
      - name: pkg-build-push
        run: |
          sudo docker --version
          cd ./ret
          org="biome-sh";repo="biome"
          ver=$(curl -s https://api.github.com/repos/$org/$repo/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3)}')
          dl="https://github.com/$org/$repo/releases/download/$ver/bio-$ver-x86_64-linux.tar.gz"
          echo "[info] getting bio from: $dl"
          curl -L -o bio.gz $dl;
          tar -xf bio.gz;./bio --version
          
          sudo ./bio origin key generate dummy1
          sudo HAB_ORIGIN_KEYS=dummy1 HAB_ORIGIN=dummy1 ./bio pkg build . > /dev/null
          sudo HAB_ORIGIN_KEYS=dummy1 HAB_ORIGIN=dummy1 ./bio pkg export container ./results/*.hart
          sudo docker images



