#

name: ret
on:
  push:
    branches: [ master, dev ]
    paths:
    - '.github/workflows/ret.yml'
  workflow_dispatch:

env:
  containerName: ret
  registryName: mozillareality

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIO_PKG_ORG: dummy1

    steps:
      - name: checkout-ret
        uses: actions/checkout@v2
        with:
          repository: mozilla/reticulum
          ref: feature/turkey
          path: './ret'
      - name: docker
        run: |
          cd ./ret           
          docker build -t $registryName/$containerName:$GITHUB_RUN_NUMBER .          
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          sudo docker images
          sudo docker push $registryName/$containerName:$GITHUB_RUN_NUMBER
  push-dev:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to dev, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
          docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev
          sudo docker push $registryName/$containerName:dev
  push-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: push-dev
    environment:
      name: prod
    steps:
      - name: pull <GITHUB_RUN_NUMBER>, re-tag to prod, push
        run: |
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
          docker pull $registryName/$containerName:$GITHUB_RUN_NUMBER
          docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod
          sudo docker push $registryName/$containerName:prod
          


