name: turkeyauth
on:
  push:
    branches: [ master ]
    paths:
    - 'auth/**'
    - '.github/workflows/turkeyauth.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: auth
      registry: mozillareality
      dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}

# # This is a basic workflow to help you get started with Actions

# name: auth

# on:
#   push:
#     branches: [ master, dev ]
#     paths:
#     - 'auth/**'
#     - '.github/workflows/auth.yml'
#   workflow_dispatch:

# env:
#   containerName: turkeyauth
#   registryName: mozillareality
#   eksName: turkey-dev

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: docker build
#         run: |
#           cd ./auth
#           docker build -q -t mozillareality/$containerName:$GITHUB_RUN_NUMBER .
#           echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin             
#           sudo docker images
#           sudo docker push $registryName/$containerName:$GITHUB_RUN_NUMBER          
#           echo "GITHUB_REF==$GITHUB_REF"
#           if [ "$GITHUB_REF" = "refs/heads/dev" ] || [ "$GITHUB_REF" = "refs/heads/master" ]; then
#             echo "pushing :dev for $GITHUB_REF"
#             docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:dev
#             sudo docker push $registryName/$containerName:dev; fi
#           if [ "$GITHUB_REF" = "refs/heads/master" ]; then
#             echo "pushing :prod for $GITHUB_REF"
#             docker tag $registryName/$containerName:$GITHUB_RUN_NUMBER $registryName/$containerName:prod
#             sudo docker push $registryName/$containerName:prod; fi          
#   deploy-dev:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: dev
#     steps:
#       - name: deploy container to dev cluster
#         run: |
#           export AWS_DEFAULT_REGION=us-east-1
#           export AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#           export AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#           aws eks update-kubeconfig --name $eksName
#           kubectl -n turkey-services set image deployment/auth turkeyauth=$registryName/$containerName:$GITHUB_RUN_NUMBER
