name: turkeyorch
on:
  push:
    branches:  
    paths:
    - 'orch/**'
    - '.github/workflows/turkeyorch.yml'
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      codePath: orch
      registry: mozilla
      dockerfile: Dockerfile
      DOCKER_HUB_USR: mzcshubs
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD_MOZ }}
