# This is a basic workflow to help you get started with Actions

name: api

on:
  push:
    branches: [ master, staging, dev ]
    paths:
    - 'yamls/**'
    - '.github/workflows/yamls.yml'
  workflow_dispatch:

env:
  s3bkt: turkeycfg

jobs:
  deploy-dev:
    # strategy:
    #   matrix:
    #     ghaEnv: [dev, staging, prod]
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: deploy container to dev cluster
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          cd ./yamls
          env=dev s3bkt=$s3bkt bash push_s3.sh
